<a href="https://colab.research.google.com/github/samyu-123/AI-amrita/blob/main/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy Tutorial :-**

In [ ]:
import numpy as np

**Lists**

In [ ]:
PythonList = [11,91,84,32]
print(PythonList)

[11, 91, 84, 32]


**Numpy**

In [ ]:
numpy_array = np.array(PythonList)
numpy_array

array([11, 91, 84, 32])

In [ ]:
a = numpy_array+20
print(a)


[ 31 111 104  52]


In [ ]:
a = np.array([11,51,90])
print(a)

[11 51 90]


In [ ]:
b = a +30
print(b)

[ 41  81 120]


In [ ]:
print(a.shape)
print(a.dtype)

(3,)
int64


In [ ]:
c = np.array([(11,22,8,0),
              (41,52,6,10)])
print(c)

[[11 22  8  0]
 [41 52  6 10]]


In [ ]:
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
      [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)

(2, 2, 3)


**TO PRINT 3 ROWS 3 COULMNS OF ZEROS**

In [ ]:
x=np.ones((3,3), dtype=np.int16)
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


**TO PRINT 3 TIMES OF 2 ROWS 4 COLUMNS OF ONES**

In [ ]:
y=np.ones((3,2,4), dtype=np.int16)
print(y)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


**RESHAPE TO 1 ELEMENT LISTS**

In [ ]:
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
print(e)

[[1 2 3]
 [4 5 6]]


In [ ]:
print('First row:', e[0])
print('Second row:', e[1])

First row: [1 2 3]
Second row: [4 5 6]


In [ ]:
print('Second column:', e[:,1])

Second column: [2 5]


In [ ]:
print(e[1, :2])

[4 5]


In [ ]:
e.flatten()

array([1, 2, 3, 4, 5, 6])

**HORITONTAL AND VERTICAL STACK**

In [ ]:
f = np.array([1,2,3])
g = np.array([4,5,6])
print('Horizontal Append:', np.hstack((f, g)))
print("Vertical append:")
print(np.vstack((f,g)))

Horizontal Append: [1 2 3 4 5 6]
Vertical append:
[[1 2 3]
 [4 5 6]]


**TO FIND A LIST OF RANDOM ELEMENTS**

In [ ]:
normal_array = np.random.normal(10,20.5,30)
print(normal_array)

[ 18.25814018   9.9403048    5.59957363  11.5022933  -23.17995981
 -22.02437646   5.93340834  -9.3157252    3.2615955   19.66173146
  13.51169511  29.27980942 -13.98092215  -5.54437704  31.00321532
  33.49113112   2.89528388   8.41963154  15.56372822  20.08590369
  30.01282011  30.15015523  49.85763548  38.95901131   0.96037659
   7.88905541  49.90935305  38.4682612   20.98785038  -5.02047288]


**FIND MIN , MAX, MEAN, MEDIAN,STD FROM  LISTS**

In [ ]:
print(np.min(normal_array))
print(np.max(normal_array))
print(np.mean(normal_array))
print(np.median(normal_array))
print(np.std(normal_array))

-23.179959809177525
49.909353054259924
13.884537690436053
12.506994202983048
18.92166716047016


**TO PRINT ELEMENTS IN RANGE**

In [ ]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1, 11,20)

array([1])

In [ ]:
np.linspace(1.0, 20.0, num=30)

array([ 1.        ,  1.65517241,  2.31034483,  2.96551724,  3.62068966,
        4.27586207,  4.93103448,  5.5862069 ,  6.24137931,  6.89655172,
        7.55172414,  8.20689655,  8.86206897,  9.51724138, 10.17241379,
       10.82758621, 11.48275862, 12.13793103, 12.79310345, 13.44827586,
       14.10344828, 14.75862069, 15.4137931 , 16.06896552, 16.72413793,
       17.37931034, 18.03448276, 18.68965517, 19.34482759, 20.        ])

In [ ]:
np.linspace(1.0, 10.0, num=10, endpoint=False)

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [ ]:
np.logspace(10.0, 5.0, num=1)

array([1.e+10])

In [ ]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize

16

**TO FIND DOT PRODUCT OF MATRIX**

In [ ]:
f = np.array([1,2,3])
g = np.array([4,5,6])
### 1*4+2*5+3*1
np.dot(f, g)

32

**TO FIND THE INVERSE OF MATRIX**

In [ ]:
A = np.array([[-1, 10, 6],
              [3, -2, 10],
              [-2, 8, -7]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[-0.33673469  0.60204082  0.57142857]
 [ 0.00510204  0.09693878  0.14285714]
 [ 0.10204082 -0.06122449 -0.14285714]]


**TO FIND THE MATRIX MULTIPLICATION**

In [ ]:
h = [[2,4],[4,6]] 
i = [[6,8,],[8,10]] 
### 1*5+2*7 = 19
np.matmul(h, i)

array([[44, 56],
       [72, 92]])

 **TO FIND THE DETERMINANT OF MATRIX**

In [ ]:
n_array = np.array([[100, 29], [30, 90]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[100  29]
 [ 30  90]]

Determinant of given 2X2 matrix:
8130


**TO FIND THE RANK OF MATRIX**

In [ ]:
mx = np.array([[2,1,1],[3,1,4],[11,4,9]])

# Let's get rank of matrix 
np.linalg.matrix_rank(mx)

3

**TO FIND THE TRANSPOSE OF THE MATRIX**

In [ ]:
gfg = np.matrix('[2, 1; 11, 3]')
              
# applying matrix.transpose() method
trans = gfg.transpose()
    
print(trans)

[[ 2 11]
 [ 1  3]]


**TO FIND THE TRACE OF MATRIX**

In [ ]:
gfg = np.matrix('[3, 2; 11, 3]')
              
# applying matrix.trace() method
tracem = gfg.trace()
    
print(tracem)

[[6]]


**TO FIND THE EIGEN VALUES AND EIGEN VECTORS OF MATRIX**

In [ ]:
example_matrix = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00 -5.14138333e-16 -2.08943529e-15] [[-0.15115432 -0.72704996  0.01790738 -0.26832672]
 [-0.34923733 -0.28320876  0.38415354  0.71367217]
 [-0.54732033  0.16063243 -0.82202921 -0.62236419]
 [-0.74540333  0.60447363  0.41996829  0.17701873]]
